# This is a basic workflow to build the Hugo site

name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.124.1'

      # Build the site with Hugo
      - name: Build site
        run: hugo --minify

      # Deploy to GitHub Pages (using the public folder directly to the main branch)
      - name: Deploy to GitHub Pages
        uses: gittools/actions/git-publish-subdir-action@v2
        with:
          branch: main           # push to the main branch
          folder: public         # push the public folder
          github_token: ${{ secrets.GITHUB_TOKEN }} 
    
